# paths to include during linting. `--path` is ignored if present.
included:
  - LMVVM

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - LMVVMTests

disabled_rules:
  - shorthand_operator

line_length:
  warning: 180
  error: 200
  ignores_comments: true

# reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
reporter: "emoji"
