language: objective-c
osx_image: xcode9.2
xcode_scheme: LMVVMTests
xcode_project: LMVVM.xcodeproj
before_install:
  - export LANG=en_US.UTF-8
  - brew install swiftlint
  - sudo gem install slather --no-ri --no-rdoc
after_success:
  - codecov
