os: osx
osx_image: xcode10.2
language: swift

env:
  matrix:
    - OS=11.4 NAME='iPad Pro (12.9-inch)'
    - OS=11.4 NAME='iPhone X'
    - OS=12.2 NAME='iPad Pro (12.9-inch) (3rd generation)'
    - OS=12.2 NAME='iPhone XÊ€'
    

before_install:
  - gem install slather --no-document

script:
  - set -o pipefail && xcodebuild -enableCodeCoverage YES -project LMVVM.xcodeproj -scheme LMVVM -sdk iphonesimulator -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES build test | xcpretty -c --test --color

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
